/**
 * ExportModal — Export pipeline as YAML, K8s manifest, Docker Compose, or CLI command
 * Blueprint Engineering Theme
 */
import { useState } from 'react';
import { X, Copy, Download, FileText, Package, Code2, Terminal, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  open: boolean;
  onClose: () => void;
  pipelineName: string;
  yaml: string;
  k8sManifest: string;
  json: string;
}

type Tab = 'yaml' | 'k8s' | 'docker' | 'cli' | 'json';

const TABS: { id: Tab; label: string; icon: React.ElementType }[] = [
  { id: 'yaml', label: 'Pipeline YAML', icon: FileText },
  { id: 'k8s', label: 'Kubernetes', icon: Package },
  { id: 'docker', label: 'Docker Compose', icon: Code2 },
  { id: 'cli', label: 'CLI Commands', icon: Terminal },
  { id: 'json', label: 'JSON', icon: FileText },
];

export default function ExportModal({ open, onClose, pipelineName, yaml, k8sManifest, json }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>('yaml');
  const [copied, setCopied] = useState(false);

  const dockerCompose = `# Docker Compose — ${pipelineName}
# Generated by FlowML

version: "3.9"

services:
  model-server:
    image: your-org/${pipelineName}:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - MODEL_NAME=${pipelineName}
      - LOG_LEVEL=info
      - METRICS_PORT=9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=flowml
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
`;

  const cliCommands = `# FlowML CLI — ${pipelineName}
# Install: pip install flowml-cli

# ── Initialize ────────────────────────────────────────────────────────────────
flowml init ${pipelineName}
cd ${pipelineName}

# ── Run locally ───────────────────────────────────────────────────────────────
flowml run pipeline.yaml

# Run with custom config
flowml run pipeline.yaml \\
  --env production \\
  --log-level debug \\
  --output ./artifacts

# ── Build Docker image ────────────────────────────────────────────────────────
flowml build \\
  --name ${pipelineName} \\
  --tag v1.0.0 \\
  --push

# ── Deploy to Kubernetes ──────────────────────────────────────────────────────
flowml deploy \\
  --cluster my-k8s-cluster \\
  --namespace ml-models \\
  --strategy rolling \\
  --replicas 3

# Canary deployment (10% traffic)
flowml deploy \\
  --strategy canary \\
  --canary-weight 10 \\
  --namespace ml-models

# Blue/green deployment
flowml deploy \\
  --strategy blue-green \\
  --namespace ml-models

# ── Monitor ───────────────────────────────────────────────────────────────────
flowml status ${pipelineName}
flowml logs ${pipelineName} --follow
flowml metrics ${pipelineName} --window 1h

# ── Rollback ──────────────────────────────────────────────────────────────────
flowml rollback ${pipelineName} --to v0.9.0

# ── Scale ─────────────────────────────────────────────────────────────────────
flowml scale ${pipelineName} --replicas 5

# ── Drift detection ───────────────────────────────────────────────────────────
flowml drift check ${pipelineName} \\
  --reference ./data/reference.parquet \\
  --current ./data/current.parquet \\
  --threshold 0.1
`;

  const content: Record<Tab, string> = {
    yaml,
    k8s: k8sManifest,
    docker: dockerCompose,
    cli: cliCommands,
    json,
  };

  const filenames: Record<Tab, string> = {
    yaml: `${pipelineName}.yaml`,
    k8s: `${pipelineName}-k8s.yaml`,
    docker: `docker-compose.yml`,
    cli: `${pipelineName}-cli.sh`,
    json: `${pipelineName}.json`,
  };

  const copyContent = () => {
    navigator.clipboard.writeText(content[activeTab]).then(() => {
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const downloadContent = () => {
    const blob = new Blob([content[activeTab]], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filenames[activeTab];
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filenames[activeTab]}`);
  };

  if (!open) return null;

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center"
        >
          {/* Backdrop */}
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 8 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 8 }}
            transition={{ duration: 0.2, ease: [0.23, 1, 0.32, 1] }}
            className="relative w-[800px] max-h-[80vh] flex flex-col rounded-xl
              bg-[#0d1220] border border-white/10 shadow-2xl overflow-hidden"
          >
            {/* Header */}
            <div className="flex items-center gap-3 px-5 py-3 border-b border-white/8">
              <Download size={14} className="text-cyan-400" />
              <span className="text-sm font-mono font-semibold text-slate-200">Export Pipeline</span>
              <span className="text-xs font-mono text-slate-600">{pipelineName}</span>
              <div className="flex-1" />
              <button
                onClick={copyContent}
                className="flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-mono
                  text-slate-400 hover:text-slate-200 border border-white/8 hover:border-white/15
                  hover:bg-white/5 transition-all"
              >
                {copied ? <CheckCircle size={11} className="text-emerald-400" /> : <Copy size={11} />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={downloadContent}
                className="flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-mono
                  bg-cyan-500/15 text-cyan-400 border border-cyan-500/30 hover:bg-cyan-500/25
                  transition-all"
              >
                <Download size={11} />
                Download
              </button>
              <button
                onClick={onClose}
                className="p-1 rounded text-slate-600 hover:text-slate-300 hover:bg-white/5 transition-all"
              >
                <X size={14} />
              </button>
            </div>

            {/* Tabs */}
            <div className="flex items-center gap-0.5 px-4 pt-2 border-b border-white/8">
              {TABS.map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-t text-xs font-mono transition-all
                    ${activeTab === tab.id
                      ? 'text-cyan-400 bg-cyan-500/10 border-b-2 border-cyan-500'
                      : 'text-slate-500 hover:text-slate-300'
                    }`}
                >
                  <tab.icon size={11} />
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Content */}
            <div className="flex-1 overflow-auto">
              <pre className="p-4 text-xs font-mono text-slate-300 leading-relaxed whitespace-pre-wrap">
                {content[activeTab]}
              </pre>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
