/**
 * ExportModal — Export pipeline as YAML, K8s manifest, Docker Compose, or CLI command
 * Editorial Precision Theme: white, black, minimal
 */
import { useState } from 'react';
import { X, Copy, Download, FileText, Package, Code2, Terminal, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  open: boolean;
  onClose: () => void;
  pipelineName: string;
  yaml: string;
  k8sManifest: string;
  json: string;
}

type Tab = 'yaml' | 'k8s' | 'docker' | 'cli' | 'json';

const TABS: { id: Tab; label: string; icon: React.ElementType }[] = [
  { id: 'yaml', label: 'Pipeline YAML', icon: FileText },
  { id: 'k8s', label: 'Kubernetes', icon: Package },
  { id: 'docker', label: 'Docker Compose', icon: Code2 },
  { id: 'cli', label: 'CLI Commands', icon: Terminal },
  { id: 'json', label: 'JSON', icon: FileText },
];

export default function ExportModal({ open, onClose, pipelineName, yaml, k8sManifest, json }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>('yaml');
  const [copied, setCopied] = useState(false);

  const dockerCompose = `# Docker Compose — ${pipelineName}
# Generated by FlowML

version: "3.9"

services:
  model-server:
    image: your-org/${pipelineName}:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - MODEL_NAME=${pipelineName}
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
`;

  const cliCommands = `# FlowML CLI — ${pipelineName}
# Install: pip install flowml-cli

flowml init ${pipelineName}
cd ${pipelineName}

# Run locally
flowml run pipeline.yaml

# Build Docker image
flowml build --name ${pipelineName} --tag v1.0.0 --push

# Deploy to Kubernetes
flowml deploy \\
  --cluster my-k8s-cluster \\
  --namespace ml-models \\
  --strategy rolling \\
  --replicas 3

# Monitor
flowml status ${pipelineName}
flowml logs ${pipelineName} --follow
flowml metrics ${pipelineName} --window 1h

# Rollback
flowml rollback ${pipelineName} --to v0.9.0
`;

  const content: Record<Tab, string> = {
    yaml,
    k8s: k8sManifest,
    docker: dockerCompose,
    cli: cliCommands,
    json,
  };

  const filenames: Record<Tab, string> = {
    yaml: `${pipelineName}.yaml`,
    k8s: `${pipelineName}-k8s.yaml`,
    docker: `docker-compose.yml`,
    cli: `${pipelineName}-cli.sh`,
    json: `${pipelineName}.json`,
  };

  const copyContent = () => {
    navigator.clipboard.writeText(content[activeTab]).then(() => {
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const downloadContent = () => {
    const blob = new Blob([content[activeTab]], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filenames[activeTab];
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filenames[activeTab]}`);
  };

  if (!open) return null;

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          style={{ position: 'fixed', inset: 0, zIndex: 50, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
        >
          {/* Backdrop */}
          <div
            style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.4)' }}
            onClick={onClose}
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.97, y: 8 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.97, y: 8 }}
            transition={{ duration: 0.18, ease: [0.23, 1, 0.32, 1] }}
            style={{
              position: 'relative',
              width: 800,
              maxHeight: '80vh',
              display: 'flex',
              flexDirection: 'column',
              borderRadius: 4,
              background: '#FFFFFF',
              border: '1px solid #E5E5E5',
              boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
              overflow: 'hidden',
            }}
          >
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 16px', borderBottom: '1px solid #E5E5E5', flexShrink: 0 }}>
              <Download size={13} color="#E8000D" />
              <span style={{ fontSize: 13, fontWeight: 600, color: '#0A0A0A' }}>Export Pipeline</span>
              <span style={{ fontSize: 12, fontFamily: "'JetBrains Mono', monospace", color: '#A3A3A3' }}>{pipelineName}</span>
              <div style={{ flex: 1 }} />
              <button
                onClick={copyContent}
                style={{
                  display: 'inline-flex', alignItems: 'center', gap: 5,
                  padding: '4px 10px', borderRadius: 3, fontSize: 12,
                  background: '#FFFFFF', border: '1px solid #E5E5E5',
                  color: '#0A0A0A', cursor: 'pointer',
                }}
                onMouseEnter={e => (e.currentTarget.style.background = '#F9F9F9')}
                onMouseLeave={e => (e.currentTarget.style.background = '#FFFFFF')}
              >
                {copied ? <CheckCircle size={11} color="#059669" /> : <Copy size={11} />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={downloadContent}
                style={{
                  display: 'inline-flex', alignItems: 'center', gap: 5,
                  padding: '4px 10px', borderRadius: 3, fontSize: 12,
                  background: '#E8000D', border: '1px solid #E8000D',
                  color: '#FFFFFF', cursor: 'pointer', fontWeight: 600,
                }}
              >
                <Download size={11} />
                Download
              </button>
              <button
                onClick={onClose}
                style={{ padding: 5, borderRadius: 3, background: 'transparent', border: 'none', cursor: 'pointer', color: '#6B6B6B', display: 'flex' }}
                onMouseEnter={e => (e.currentTarget.style.background = '#F4F4F4')}
                onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
              >
                <X size={14} />
              </button>
            </div>

            {/* Tabs */}
            <div style={{ display: 'flex', alignItems: 'center', padding: '0 16px', borderBottom: '1px solid #E5E5E5', flexShrink: 0 }}>
              {TABS.map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  style={{
                    display: 'inline-flex', alignItems: 'center', gap: 5,
                    padding: '8px 12px', fontSize: 12, cursor: 'pointer',
                    background: 'transparent', border: 'none',
                    borderBottom: activeTab === tab.id ? '2px solid #E8000D' : '2px solid transparent',
                    color: activeTab === tab.id ? '#0A0A0A' : '#6B6B6B',
                    fontWeight: activeTab === tab.id ? 600 : 400,
                    transition: 'color 120ms',
                    fontFamily: "'Inter', sans-serif",
                  }}
                >
                  <tab.icon size={11} />
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Content */}
            <div style={{ flex: 1, overflow: 'auto', background: '#FAFAFA' }}>
              <pre style={{
                padding: 16,
                fontSize: 12,
                fontFamily: "'JetBrains Mono', monospace",
                color: '#0A0A0A',
                lineHeight: 1.7,
                whiteSpace: 'pre-wrap',
                margin: 0,
              }}>
                {content[activeTab]}
              </pre>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
